const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
});

const sendWelcomeEmail = async (toEmail, name, role, defaultPassword) => {
  try {
    const roleCapitalized = role.charAt(0).toUpperCase() + role.slice(1);
    
    const mailOptions = {
      from: `"NIMS University ERP" <${process.env.EMAIL_USER}>`,
      to: toEmail,
      subject: `Welcome to NIMS University - Your ${roleCapitalized} Account`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;">
          <div style="background-color: #D90429; padding: 20px; text-align: center;">
            <h1 style="color: #ffffff; margin: 0;">NIMS University</h1>
            <p style="color: #ffcccc; margin: 5px 0 0 0;">Educating Minds, Shaping Futures</p>
          </div>
          <div style="padding: 30px; background-color: #ffffff;">
            <h2 style="color: #111827;">Hello ${name},</h2>
            <p style="color: #4b5563; line-height: 1.6;">
              Welcome to the NIMS University ERP System! Your official <strong>${roleCapitalized}</strong> account has been successfully created by the administration.
            </p>
            
            <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 25px 0;">
              <h3 style="margin-top: 0; color: #111827;">Your Login Credentials</h3>
              <p style="margin-bottom: 5px; color: #4b5563;"><strong>Login ID (Email):</strong> ${toEmail}</p>
              <p style="margin-bottom: 0; color: #4b5563;"><strong>Temporary Password:</strong> ${defaultPassword}</p>
            </div>
            
            <p style="color: #4b5563; line-height: 1.6;">
              Please log in to the Mobile App using these credentials. <strong>For security reasons, we highly recommend changing your password from the Profile section immediately after your first login.</strong>
            </p>
            
            <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 30px 0;" />
            <p style="color: #9ca3af; font-size: 12px; text-align: center; margin: 0;">
              This is an automated message generated by the NIMS University ERP System. Please do not reply to this email.
            </p>
          </div>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log(`Welcome email sent to ${toEmail}: ${info.messageId}`);
    return true;
  } catch (error) {
    console.error('Error sending welcome email:', error);
    return false;
  }
};

module.exports = {
  sendWelcomeEmail,
};
